# For a quick start check out our HTTP Requests collection (Tools|HTTP Client|Open HTTP Requests Collection).
#
# Following HTTP Request Live Templates are available:
# * 'gtrp' and 'gtr' create a GET request with or without query parameters;
# * 'ptr' and 'ptrp' create a POST request with a simple or parameter-like body;
# * 'mptr' and 'fptr' create a POST request to submit a form with a text or file field (multipart/form-data);
GET {{url}}/users
Content-Type: application/json


###

GET {{url}}/user/1
Content-Type: application/json

###

POST {{url}}/users
Content-Type: application/json

{
    "name": "Ivan",
    "login": "ivan",
    "email": "ivan@gmail.com"
}

###

PUT {{url}}/user/0
Content-Type: application/json

{
    "name": "Ivan310",
    "login": "ivan318",
    "email": "ivan3@gmail.com"
}

###

DELETE {{url}}/user/0
Content-Type: application/json

###